[package]
name = "r1cs"
description = "A library for building R1CS gadgets"
version = "0.1.0"
authors = ["Daniel Lubarov <daniel@mirprotocol.org>", "Brendan Farmer <brendan@mirprotocol.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mir-protocol/r1cs"
keywords = ["r1cs", "crypto", "snarks"]
categories = ["cryptography"]
maintenance = "actively-developed"
edition = "2018"

[dependencies]
itertools = "0.8.0"
num = { version = "0.2.0", features = ["rand"] }
num-traits = "0.2.8"
rand = "0.6.5"
