name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request: ~

jobs:
  test-std:
    name: Test with std
    uses: icepuma/rust-action
    args: cargo test
  test-no-std:
    name: Test without std
    uses: icepuma/rust-action
    args: cargo test --no-default-features
  # TODO: Also run this to make sure the project compiles with a wasm target:
  # rustup target add wasm32-unknown-unknown
  # cargo check --target wasm32-unknown-unknown
