name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request: ~

jobs:
  test-std:
    name: Test with std
    steps:
      - name: Test
        uses: icepuma/rust-action
        args: cargo test
  test-no-std:
    name: Test without std
    steps:
      - name: Test
        uses: icepuma/rust-action
        args: cargo test --no-default-features
  build-wasm:
    name: Build with a WASM target
    steps:
      - name: Add target
        uses: icepuma/rust-action
        args: rustup target add wasm32-unknown-unknown
      - name: Check
        uses: icepuma/rust-action
        args: cargo check --target wasm32-unknown-unknown
