name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request: ~

jobs:
  test-std:
    name: Test with std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: icepuma/rust-action@master
        with:
          args: cargo test
  test-no-std:
    name: Test without std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: icepuma/rust-action@master
        with:
          args: cargo test --no-default-features
  build-wasm:
    name: Build with a WASM target
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for errors with a WASM target
        uses: icepuma/rust-action@master
        with:
          args: rustup target add wasm32-unknown-unknown && cargo check --target wasm32-unknown-unknown
